beezSSG/finalproject_pickme_back

src/main/resources/application.properties
=> #7 feat: 자동재빌드 설정 추가

src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MypageCouponDto.java, src/main/java/com/pickme/beeze/mypage/dto/MypageCustomerDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #11 Feature 개인정보 관련 기능 추가

src/main/java/com/pickme/beeze/product/controller/ProductController.java, src/main/java/com/pickme/beeze/product/dao/ProductDao.java, src/main/java/com/pickme/beeze/product/dto/ProductDto.java, src/main/java/com/pickme/beeze/product/service/ProductService.java, src/main/java/sqls/product.xml
=> #12 feat 신제품등록 기능 추가

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/CeoDto.java, src/main/java/com/pickme/beeze/ceo/dto/CeoParam.java, src/main/java/com/pickme/beeze/ceo/dto/PurchaseDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/java/sqls/ceo.xml
=> #17 발주 하기 기능 추가

src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #18 Feature 1:1 문의 기능 추가

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/manager/controller/EventController.java, src/main/java/com/pickme/beeze/manager/dao/EventDao.java, src/main/java/com/pickme/beeze/manager/service/EventService.java, src/main/java/sqls/event.xml
=> #16 feat 추가사항x

src/main/java/com/pickme/beeze/DatabaseConfig.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MypageOrderDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #20 Feature 마이페이지 주문내역 기능추가

src/main/java/sqls/faq.xml
=> #16 fix faq목록 불러오기 수정

pom.xml, src/main/java/com/pickme/beeze/DatabaseConfig.java, src/main/resources/application.properties
=> #22 Fix 설정관련 실행불가 에러 해결

pom.xml, src/main/java/com/pickme/beeze/PickmeApplication.java, src/main/java/com/pickme/beeze/WebConfigurer.java, src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/login/dto/LoginDto.java, src/main/java/com/pickme/beeze/login/dto/TokenDto.java, src/main/java/com/pickme/beeze/login/dto/UserDto.java, src/main/java/com/pickme/beeze/login/dto/UserLoginDto.java, src/main/java/com/pickme/beeze/login/jwt/JwtTokenFilter.java, src/main/java/com/pickme/beeze/login/jwt/JwtTokenProvider.java, src/main/java/com/pickme/beeze/login/security/CorsConfig.java, src/main/java/com/pickme/beeze/login/security/SecurityConfig.java, src/main/java/com/pickme/beeze/login/security/SecurityService.java, src/main/java/sqls/login.xml
=> #21 Feature 스프링 시큐리티 및 jwt 구현

.gitignore, pom.xml, src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/login/dao/LoginDao.java, src/main/java/com/pickme/beeze/login/service/LoginService.java, src/main/java/sqls/login.xml, src/main/resources/application.properties
=> #25 Feature 아이디 찾기 기능 추가

.gitignore, pom.xml, src/main/java/com/pickme/beeze/PickmeApplication.java, src/main/resources/application.properties
#26 Fix 민감정보 제거 및 git ignore 추가
=> #26 Fix 민감정보 제거 및 git ignore 추가

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/ProductDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/java/sqls/ceo.xml
=> #19 발주신청 기능 추가

src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/login/email/EmailConfig.java, src/main/java/com/pickme/beeze/manager/controller/CcbController.java, src/main/java/com/pickme/beeze/manager/controller/ManagerPurchaseOrderController.java, src/main/java/com/pickme/beeze/manager/dao/CcbDao.java, src/main/java/com/pickme/beeze/manager/dao/ManagerPurchaseOrderDao.java, src/main/java/com/pickme/beeze/manager/dto/ManagerPurchaseDto.java, src/main/java/com/pickme/beeze/manager/dto/ManagerPurchaseOrderParam.java, src/main/java/com/pickme/beeze/manager/service/CcbService.java, src/main/java/com/pickme/beeze/manager/service/ManagerPurchaseOrderService.java, src/main/java/sqls/ccb.xml, src/main/java/sqls/manager.xml, src/main/java/sqls/mypage.xml
=> fix/27 1:1문의 수정

pom.xml, src/main/java/com/pickme/beeze/PickmeApplication.java, src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/login/email/EmailConfig.java, src/main/java/com/pickme/beeze/login/email/MailService.java, src/main/java/com/pickme/beeze/login/service/LoginService.java, src/main/resources/application.properties
#30 Fix 이메일 인증서비스 오류 및 변경기능 추가
=> #30 Fix 이메일 인증서비스 오류 및 변경기능 추가

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/customer/dao/CustomerDao.java, src/main/java/com/pickme/beeze/customer/dto/CartDto.java, src/main/java/com/pickme/beeze/customer/service/CustomerService.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/customer.xml
=> #34 Fix 장바구니 목록 불러오기 기능 수정

src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MypageMainInfoDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #35 Feature 메인페이지 정보획득 추가

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/login/dto/LoginDto.java, src/main/java/com/pickme/beeze/mypage/dto/MypageMainInfoDto.java, src/main/java/sqls/login.xml
=> #37 Fix 회원 정보 관련 수정 및 디버깅작업

src/main/java/com/pickme/beeze/store/controller/StoreController.java, src/main/java/com/pickme/beeze/store/dao/StoreDao.java, src/main/java/com/pickme/beeze/store/service/StoreService.java, src/main/java/sqls/store.xml
=> #6 feat: 모든 매장 list 불러오기

src/main/java/com/pickme/beeze/manager/controller/CcbController.java, src/main/java/com/pickme/beeze/manager/dao/CcbDao.java, src/main/java/com/pickme/beeze/manager/dto/CcbParam.java, src/main/java/com/pickme/beeze/manager/service/CcbService.java, src/main/java/sqls/ccb.xml
=> #27 fix 관리자페이지 back 수정

src/main/java/com/pickme/beeze/manager/controller/ManagerController.java, src/main/java/com/pickme/beeze/manager/dto/OrderDto.java, src/main/java/sqls/manager.xml
=> #27 fix 그래프 월별+도시별

src/main/java/com/pickme/beeze/manager/controller/CcbController.java, src/main/java/com/pickme/beeze/manager/controller/ManagerController.java, src/main/java/com/pickme/beeze/manager/dao/ManagerDao.java, src/main/java/com/pickme/beeze/manager/dto/EventDto.java, src/main/java/com/pickme/beeze/manager/dto/EventEnddateDto.java, src/main/java/com/pickme/beeze/manager/service/ManagerService.java, src/main/java/sqls/manager.xml
=> #27 feature 종료 3일이하 이벤트개수

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/customer/dao/CustomerDao.java, src/main/java/com/pickme/beeze/customer/dto/CartDto.java, src/main/java/com/pickme/beeze/customer/service/CustomerService.java, src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MypageCustomerDto.java, src/main/java/com/pickme/beeze/mypage/dto/MypageSaveDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/com/pickme/beeze/util/InfoUtil.java, src/main/java/sqls/customer.xml, src/main/java/sqls/mypage.xml
#38 Fix 주문완료 후 추가 작업에 대한 기능 추가
=> #38 Fix 주문완료 후 추가 작업에 대한 기능 추가

src/main/java/com/pickme/beeze/store/controller/StoreController.java, src/main/java/com/pickme/beeze/store/dao/StoreDao.java, src/main/java/com/pickme/beeze/store/service/StoreService.java, src/main/java/sqls/store.xml
=> #34 feat: 매장 검색 BE 구축

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/customer/dao/CustomerDao.java, src/main/java/com/pickme/beeze/customer/dto/PostDto.java, src/main/java/com/pickme/beeze/customer/service/CustomerService.java, src/main/java/sqls/customer.xml
=> #27 feat 택배서비스

src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #41 Fix 로그인 기능 수정

src/main/java/com/pickme/beeze/customer/dao/CustomerDao.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MypageOrderdayDto.java, src/main/java/com/pickme/beeze/mypage/dto/MypageProductDto.java, src/main/java/com/pickme/beeze/mypage/dto/MypageReviewDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #43 Feature 마이페이지 관련 기능추가

src/main/java/com/pickme/beeze/store/controller/StoreController.java, src/main/java/com/pickme/beeze/store/dao/StoreDao.java, src/main/java/com/pickme/beeze/store/dto/StoreDto.java, src/main/java/com/pickme/beeze/store/service/StoreService.java, src/main/java/sqls/store.xml
매장 이름 검색창 오류 수정 - controller 등에 String storeName이라는 인수를 추가
=> Fix/39 매장 검색페이지 - 매장 이름 검색창 오류 수정

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/customer/dao/CustomerDao.java, src/main/java/com/pickme/beeze/customer/service/CustomerService.java, src/main/java/com/pickme/beeze/product/dto/ProductDto.java, src/main/java/com/pickme/beeze/product/dto/ProductParam.java, src/main/java/sqls/customer.xml
=> #27 fix 무한스크롤 백

src/main/java/com/pickme/beeze/DatabaseConfig.java, src/main/java/com/pickme/beeze/PickmeApplication.java, src/main/java/com/pickme/beeze/login/security/SecurityConfig.java, src/main/java/com/pickme/beeze/login/service/LoginService.java, src/main/java/com/pickme/beeze/product/controller/ProductController.java, src/main/java/com/pickme/beeze/product/dao/ProductDao.java, src/main/java/com/pickme/beeze/product/dto/ProductGiftDto.java, src/main/java/com/pickme/beeze/product/dto/ProductGiftParam.java, src/main/java/com/pickme/beeze/product/service/ProductService.java, src/main/java/com/pickme/beeze/util/EmailConfig.java, src/main/java/com/pickme/beeze/util/MailService.java, src/main/java/sqls/product.xml
=> #46 Feature 선물함 기능 추가

src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/util/EmailConfig.java, src/main/java/com/pickme/beeze/util/MailService.java
=> #47 Fix 회원가입 관련기능 오류 수정

src/main/java/com/pickme/beeze/product/controller/ProductController.java, src/main/java/com/pickme/beeze/util/NaverCloud.java, src/main/java/sqls/product.xml
=> #48 Fix OCR 관련기능 오류 수정

src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/login/dao/LoginDao.java, src/main/java/com/pickme/beeze/login/dto/OcrListDto.java, src/main/java/com/pickme/beeze/login/service/LoginService.java, src/main/java/sqls/login.xml
=> #27 fix 사업자 등록

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/customer/dao/CustomerDao.java, src/main/java/com/pickme/beeze/customer/dto/CartDto.java, src/main/java/com/pickme/beeze/login/jwt/JwtTokenFilter.java, src/main/java/com/pickme/beeze/login/jwt/JwtTokenProvider.java, src/main/java/com/pickme/beeze/login/security/SecurityConfig.java, src/main/java/com/pickme/beeze/login/security/SecurityService.java, src/main/java/com/pickme/beeze/product/controller/ProductController.java, src/main/java/sqls/mypage.xml, src/main/java/sqls/product.xml
=> #51 Fix JWT 배포전 에러 수정

src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MypageOrderdayDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #52 Fix 결제정보 정보추가

src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MypageOrderdayDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #53 Fix 결제정보 추가수정

src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MyPickBoxDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/sqls/mypage.xml
=> #56 Feature 픽박스 기능추가

src/main/java/sqls/store.xml
store.xml를 통째로 이동시켜서 local 환경에서도 사용할 수 있도록 복사 붙여넣기함
=> #54 fix: store.xml 복사

src/main/java/com/pickme/beeze/util/S3Service.java
=> #58 aws 추가 커밋

src/main/java/com/pickme/beeze/manager/controller/CouponController.java, src/main/java/com/pickme/beeze/manager/dao/CouponDao.java, src/main/java/com/pickme/beeze/manager/dto/CouponDto.java, src/main/java/com/pickme/beeze/manager/service/CouponService.java, src/main/resources/sqls/coupon.xml
=> #27 feat 쿠폰 생성

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/CeoInfoDto.java, src/main/java/com/pickme/beeze/ceo/dto/InventoryDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/resources/sqls/ceo.xml
=> 재고 현황 레이아웃 완성

.github/workflows/cicd.yaml
=> testcommit

src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/login/dao/LoginDao.java, src/main/java/com/pickme/beeze/login/service/LoginService.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/resources/sqls/login.xml, src/main/resources/sqls/mypage.xml
=> #60 Fix 마이페이지 수정

.github/workflows/cicd.yaml, src/main/java/com/pickme/beeze/login/controller/LoginController.java, src/main/java/com/pickme/beeze/login/dao/LoginDao.java, src/main/java/com/pickme/beeze/login/service/LoginService.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/resources/sqls/login.xml, src/main/resources/sqls/mypage.xml
=> dev -> main commit & push

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/OrderDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/resources/sqls/ceo.xml
=> 픽업기능 레이아웃  구현하기

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/PostDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/resources/sqls/ceo.xml
=> 배달 기능 레이아웃 구현

src/main/java/com/pickme/beeze/store/controller/StoreController.java, src/main/java/com/pickme/beeze/store/dao/StoreDao.java, src/main/java/com/pickme/beeze/store/service/StoreService.java, src/main/resources/sqls/store.xml
<br/>
<br/>
-  매장 검색 쿼리문 수정
-  Store dao, service, controller의 searchstore() 함수에 stateName(도/시 이름), districtName(구 이름) parameter 추가
<br/>
- BE는 없음!
<br/>
- [finalproject_pickme_back #155 ](https://github.com/beezSSG/finalproject_pickme_back/issues/155#issue-2239022993)
<br/>
=> #59 fix: 매장 검색 BE 수정

src/main/java/com/pickme/beeze/mypage/dto/MypageCouponDto.java, src/main/resources/sqls/coupon.xml, src/main/resources/sqls/mypage.xml
#27 fix 쿠폰 쿼리문 수정
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #27 fix 쿠폰 쿼리문 수정

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dto/OrderDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/resources/sqls/ceo.xml
<br/>
- 승인완료 물품 사라지기 
- date 형식 수정
<br/>
- 프론트로도 구현 완료
<br/>
- [finalproject_pickme_back #63 ](이슈 주소)
<br/>
=> #63 Feat&Fix 승인완료 물품 사라지기 / date 형식 수정

src/main/java/com/pickme/beeze/WebConfigurer.java, src/main/resources/sqls/store.xml
<br/>
- 전체 매장 데이터를 들고 올때 시작, 종료 시간을 들고 오게 쿼리문 살 ~ 짝 수정
<br/>
<br/>
<br/>
=> feat(issue66) :  전체 매장 조회 시 sql 값 추가 (start, end)

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/customer/dao/CustomerDao.java, src/main/java/com/pickme/beeze/customer/service/CustomerService.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/java/com/pickme/beeze/mypage/dao/MypageDao.java, src/main/java/com/pickme/beeze/mypage/dto/MypageCouponDto.java, src/main/java/com/pickme/beeze/mypage/service/MypageService.java, src/main/java/com/pickme/beeze/product/controller/ProductController.java, src/main/resources/sqls/coupon.xml, src/main/resources/sqls/customer.xml, src/main/resources/sqls/mypage.xml, src/main/resources/sqls/product.xml
<br/>
<br/>
- 마이페이지에서 자주 발생했던 버그들에 대한 디버그 작업을 했습니다.
<br/>
- 추가적인 버그를 발견하여 더많은 디버깅 작업이 필요합니다.
<br/>
- [finalproject_pickme_back #171 ]
<br/>
=> #65 Fix 마이페이지 관련 기능 디버깅

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/InventoryDto.java, src/main/java/com/pickme/beeze/ceo/dto/ProductDto.java, src/main/java/com/pickme/beeze/ceo/dto/PurchaseDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/java/com/pickme/beeze/mypage/controller/MypageController.java, src/main/resources/sqls/ceo.xml
<br/>
-  발주하기 완료했습니다!
<br/>
- 재고 현황 좀 봐야겠네요
<br/>
<br/>
=> 170 64 feature 발주하기 완료하기

src/main/resources/sqls/store.xml
#77 메인화면 버그 픽스 뷰에서 처리하던걸 그냥 서버에서 처리하게 수정
=> #77 메인화면 버그 픽스

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/resources/sqls/manager.xml
#27 fix 수정완(발주신청)
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #27 fix 수정완(발주신청)

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dto/CeoParam.java, src/main/resources/sqls/ceo.xml, src/main/resources/sqls/product.xml
=> #67 Fix 전반적인 디버깅 작업 실시

pom.xml, src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/OrderDto.java, src/main/java/com/pickme/beeze/ceo/dto/PostDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/resources/sqls/ceo.xml
<br/>
- 픽업/배달 페이지네이션
<br/>
- 픽업/배달 페이지네이션
<br/>
<br/>
=> 186 69 feature 픽업/배달 페이지네이션

src/main/java/com/pickme/beeze/customer/dto/ProductReservationDto.java
#27 feat 일단 커밋
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #27 feat 일단 커밋

src/main/java/com/pickme/beeze/customer/controller/CustomerController.java, src/main/java/com/pickme/beeze/customer/dao/CustomerDao.java, src/main/java/com/pickme/beeze/customer/service/CustomerService.java, src/main/resources/sqls/customer.xml
#71 fix 상품예약후 db저장
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #71 fix 상품예약후 db저장

src/main/java/com/pickme/beeze/customer/dto/ProductReservationDto.java
#71 fix 상품예약
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #71 fix 상품예약

src/main/java/com/pickme/beeze/product/controller/ProductController.java, src/main/java/com/pickme/beeze/product/dao/ProductDao.java, src/main/java/com/pickme/beeze/product/service/ProductService.java, src/main/resources/sqls/product.xml
<br/>
<br/>
- 메인홈 행사상품 섹션에서 선택한 태그값에 따라 1은 1+1, 2는 2+1, 3은 신상품으로 각각 15개씩 보여주도록 함
<br/>
- 
<br/>
- [finalproject_pickme_back #70](https://github.com/beezSSG/finalproject_pickme_back/issues/191#issue-2249617637)
<br/>
=> #70 feat: 메인홈 - 행사상품

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/java/com/pickme/beeze/customer/dto/ProductReservationDto.java, src/main/resources/sqls/ceo.xml
#71 fix 상품예약 목록/승인
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #71 fix 상품예약 목록/승인

src/main/resources/sqls/store.xml
=> #67 Fix 전반적인 코드 수정

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/OrderDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/resources/sqls/ceo.xml
픽업/배달 승인 확인
<br/>
<br/>
- check_yn 추가되었습니다 default값은 0
- date를 parameter로 들고오는 것으로 수정했습니다
<br/>
- alert창 예쁘게 꾸미기
<br/>
<br/>
=> #68 픽업/배달 승인 확인

src/main/resources/sqls/customer.xml
#71 fix 택배예약
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #71 fix 택배예약

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dao/CeoDao.java, src/main/java/com/pickme/beeze/ceo/dto/PostDto.java, src/main/java/com/pickme/beeze/ceo/service/CeoService.java, src/main/resources/sqls/ceo.xml
택배예약 승인 alert
<br/>
<br/>
- 택배예약 승인 alert
<br/>
<br/>
<br/>
=> #69 택배예약 승인 alert

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java
#71 fix 살려
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #71 fix 살려

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java
#27 feat 픽업배달
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #27 feat 픽업배달

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java
#27 fix 픽업/배달
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #27 fix 픽업/배달

src/main/java/com/pickme/beeze/customer/dto/PostDto.java, src/main/resources/sqls/ceo.xml, src/main/resources/sqls/customer.xml
#27 feat 택배 신청 스토어아이디 추가
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #27 feat 택배 신청 스토어아이디 추가

src/main/java/com/pickme/beeze/ceo/dto/PostDto.java, src/main/java/com/pickme/beeze/manager/dto/EventDto.java, src/main/resources/sqls/event.xml
#27 각종 버그 수정
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #27 각종 버그 수정

src/main/java/com/pickme/beeze/customer/dto/ProductReservationDto.java, src/main/resources/sqls/customer.xml
#27 fix 상품예약 끝
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #27 fix 상품예약 끝

src/main/resources/sqls/login.xml
#67 백엔드 디버깅작업실시
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
<br/>
=> #67 백엔드 디버깅작업실시

src/main/java/com/pickme/beeze/ceo/controller/CeoController.java, src/main/java/com/pickme/beeze/ceo/dto/InventoryDto.java, src/main/resources/sqls/ceo.xml
<br/>
- 발주내역 정렬 수정
- 재고 정렬 수정 
<br/>
<br/>
<br/>
=> 206 74 feature 택배예약 확인 alert창 뜨게하기
